webapp/src/web/views/admin.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, Markup, Response
from flask import current_app as app

from functools import wraps
import json
import sqlite3
import pdb

import time

from collections import defaultdict
import operator

from cocoa.web.views.utils import userid, format_message
from cocoa.web.main.utils import Status
from cocoa.core.event import Event

from main.db_reader import DatabaseReader

from web.main.backend import Backend
get_backend = Backend.get_backend

admin = Blueprint('admin', __name__)


@admin.route('/_accept/', methods=['GET'])
def accept():
    chat_id = request.args.get('chat_id')
    review_status = request.args.get('review_status')

    db_path = app.config['user_params']['db']['location']
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    if int(review_status) >= 0:
        cursor.execute(
            ''' UPDATE review
            SET accept=1
            where chat_id=?''', (chat_id,))
    else:
        cursor.execute(
            '''INSERT INTO review VALUES (?,?, "")''', (chat_id, 1))
    conn.commit()
    return jsonify(success=True)

@admin.route('/_reject/', methods=['GET'])
def reject():
    chat_id = request.args.get('chat_id')
    review_status = request.args.get('review_status')
    reject_message = request.args.get('reject_message')

    db_path = app.config['user_params']['db']['location']
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    if int(review_status) >= 0:
        cursor.execute(
            ''' UPDATE review
            SET accept=0, message=?
            where chat_id=?''', (reject_message, chat_id,))
    else:
        cursor.execute(
            '''INSERT INTO review VALUES (?,?,?)''', (chat_id, 0, reject_message))
    conn.commit()
    return jsonify(success=True)

@admin.route('/_zero_active/', methods=['GET'])
def zero_active():
    try:
        db_path = app.config['user_params']['db']['location']
        conn = sqlite3.connect(db_path)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute('''UPDATE scenario SET active="[]"''')
        conn.commit()  
    except sqlite3.IntegrityError:
            print("WARNING: Rolled back transaction")
            return jsonify(success=False)
    return jsonify(success=True)

def _accept(cursor, chat_id):
    cursor.execute(
            '''INSERT INTO review VALUES (?,?, "")''', (chat_id, 1))
    return True

def _reject(cursor, chat_id, reject_message):
    cursor.execute(
            '''INSERT INTO review VALUES (?,?,?)''', (chat_id, 0, reject_message))
    return True


def check_auth(username, password):
    """This function is called to check if a username /
    password combination is valid.
    """
    return username == 'sample' and password == 'sample'

def authenticate():
    """Sends a 401 response that enables basic auth"""
    return Response(
    'Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

def clean_incomplete_chats(cursor):
    cursor.execute('SELECT DISTINCT chat_id FROM event')
    ids = [x[0] for x in cursor.fetchall()]
    for chat_id in ids:
        if not DatabaseReader.check_completed_info(cursor, chat_id):
            cursor.execute('DELETE FROM event where chat_id=?',(chat_id, ))

@admin.route('/admin')
@requires_auth
def visualize():
    backend = get_backend()
    db_path = app.config['user_params']['db']['location']
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    # create table review if not exists
    if not cursor.execute('''SELECT name FROM sqlite_master WHERE type='table' AND name='review' ''').fetchone():
        cursor.execute(
            '''CREATE TABLE review (chat_id text, accept integer, message text)'''
        )
        conn.commit()
        print("created new table review")

    if not request.args.get('chat_id'):
        cursor.execute('SELECT DISTINCT chat_id FROM event')
        ids = [x[0] for x in cursor.fetchall()]
        cursor.execute('SELECT DISTINCT chat_id FROM review')
        reviewed_ids = [x[0] for x in cursor.fetchall()]
        if 'incomplete' in request.args:
            # list only chat_ids which are incomplete and not reviewed yet
            ids = [chat_id for chat_id in ids if (chat_id not in reviewed_ids) and (not DatabaseReader.check_completed_info(cursor, chat_id))]
        elif 'completed' in request.args:
            # list all chat_ids which are completed
            ids = [chat_id for chat_id in ids if DatabaseReader.check_completed_info(cursor, chat_id)]
        else:
            # list only chat_ids which are completed but not reviewed yet
            ids = [chat_id for chat_id in ids if chat_id not in reviewed_ids and DatabaseReader.check_completed_info(cursor, chat_id)]
        outcomes = []
        dialogues = []
        num_success = 0
        num_fail = 0
        num_incomplete = 0
        for chat_id in ids:
            outcome = DatabaseReader.get_chat_outcome(cursor, chat_id)
            outcomes.append(outcome)
            if outcome['reward'] == 1:
                num_success += 1
            else:
                num_fail += 1
            chat_info = DatabaseReader.get_chat_example(cursor, chat_id, app.config['scenario_db'], include_meta=True).to_dict()
            chat_text = ""
            select_id = {}
            for chat_event in chat_info['events']:
                if chat_event['action'] == 'message':
                    chat_text += "{}: {}\n".format(chat_event['agent'], chat_event['data'].encode('ascii', 'ignore'))
            dialogues.append(chat_text)

        num_ids = len(ids)

        return render_template('chat_list.html',
                                num_chats = num_ids,
                                chat_ids = ids,
                                chat_outcomes = outcomes,
                                reviewed = ["" for i in range(num_ids)],
                                base_url = request.url + '?chat_id=',
                                num_success=num_success,
                                num_fail=num_fail,
                                num_incomplete=num_incomplete,
                                num_accept=0,
                                num_reject=0,
                                dialogues=dialogues)
    else:
        chat_id = request.args.get('chat_id')
        chat_info = DatabaseReader.get_chat_example(cursor, chat_id, app.config['scenario_db'], include_meta=True).to_dict()
        chat_text = ""
        select_id = {}
        for chat_event in chat_info['events']:
            if chat_event['action'] == 'message':
                chat_text += "{}: {}\n".format(chat_event['agent'], chat_event['data'].encode('ascii', 'ignore'))
            elif chat_event['action'] == 'select':
                chat_text += "<{} selected {}>\n".format(chat_event['agent'], chat_event['data'])
                select_id[chat_event['agent']] = chat_event['data']

        cursor.execute('''SELECT accept, message FROM review where chat_id=?''', (chat_id, ))
        res = cursor.fetchone()
        if res:
            review_status = res[0]
            message = res[1]
        else:
            review_status = -1
            message = ""

        select = {}
        for agent in [0,1]:
            select[agent] = None
            if agent in select_id:
                for obj in chat_info['scenario']['kbs'][agent]:
                    if obj['id'] == select_id[agent]:
                        select[agent] = obj
                        break

        cursor.execute('''SELECT * FROM survey where chat_id=?''', (chat_id, ))
        res = cursor.fetchone()
        if res:
            survey = True
            cooperative = res[3]
            humanlike = res[4]
            comments = res[5]
        else:
            survey = False
            cooperative = None
            humanlike = None
            comments = None

        return render_template('visualize.html',
                                chat_id=chat_id,
                                chat_text=chat_text,
                                kb_0=chat_info['scenario']['kbs'][0],
                                kb_1=chat_info['scenario']['kbs'][1],
                                select_0=select[0],
                                select_1=select[1],
                                review_status=review_status,
                                message=message,
                                agent_0=chat_info['agents']['0'],
                                agent_1=chat_info['agents']['1'],
                                survey=survey,
                                cooperative=cooperative,
                                humanlike=humanlike,
                                comments=comments
                                )

webapp/src/web/views/selfplay.py
from flask import Blueprint, jsonify, render_template, request, redirect, url_for, Markup, Response
from flask import current_app as app

from functools import wraps
import itertools
import json
import sqlite3
import pdb

from collections import defaultdict
import operator

from cocoa.web.views.utils import userid, format_message
from cocoa.web.main.utils import Status
from cocoa.core.event import Event

from main.db_reader import DatabaseReader

from web.main.backend import Backend
get_backend = Backend.get_backend

selfplay = Blueprint('selfplay', __name__)

def check_auth(username, password):
    """This function is called to check if a username /
    password combination is valid.
    """
    return username == 'sample' and password == 'sample'

def authenticate():
    """Sends a 401 response that enables basic auth"""
    return Response(
    'Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated


def is_annotatable_markable(markable):
    if markable["generic"] or markable["no-referent"] or markable["all-referents"] or markable["anaphora"] or markable["cataphora"] or markable["predicative"]:
        return False
    else:
        return True

def calculate_statistics(scenario_ids, selfplay_markables, selfplay_referents):
    num_markables = []
    num_referents = []
    results = []

    for scenario_id in scenario_ids:
        markables = selfplay_markables[scenario_id]['markables']
        num_markables.append(len(markables))

        num_referents_dict = defaultdict(lambda: 0)

        for markable in markables:
            markable_id = markable['markable_id']
            referents = selfplay_referents[scenario_id][markable_id]
            num_referents_dict[len(referents)] += 1

        num_referents.append(num_referents_dict)

        results.append(int(selfplay_markables[scenario_id]['selections'][0] == selfplay_markables[scenario_id]['selections'][1]))

    return num_markables, num_referents, results

@selfplay.route('/selfplay')
def selfplay_coreference_annotation():
    selfplay_scenarios = app.config['selfplay_scenarios']
    selfplay_markables = app.config['selfplay_markables']
    selfplay_referents = app.config['selfplay_referents']

    #request args
    scenario_id = request.args.get('scenario_id', default=None, type=None)

    if not scenario_id:
        scenario_ids = list(selfplay_markables.keys())

        num_markables, num_referents, results = calculate_statistics(scenario_ids, selfplay_markables, selfplay_referents)

        return render_template('selfplay_scenario_list.html',
                                num_scenarios = len(scenario_ids),
                                scenario_ids = scenario_ids,
                                base_url = 'http://localhost:5000/sample/selfplay',
                                num_markables = num_markables,
                                num_referents = num_referents,
                                results = results)
    else:
        text = selfplay_markables[scenario_id]["text"]
        markup_text = ""

        scenario = [scenario for scenario in selfplay_scenarios if scenario['uuid'] == scenario_id]
        scenario = scenario[0]

        starts = []
        ends = []
        speakers = []
        markable_ids = []
        for i, markable in enumerate(selfplay_markables[scenario_id]["markables"]):
            starts.append(int(markable["start"]))
            ends.append(int(markable["end"]))
            speakers.append(int(markable["speaker"]))
            markable_ids.append(markable["markable_id"])

        for i, ch in enumerate(text):
            if i in starts:
                markable_idx = starts.index(i)
                markup_text += "<span class=\"markable speaker_{1}\" id=\"{0}\" onclick=\"selectMarkable(\'{0}\')\">".format(markable_ids[markable_idx], speakers[markable_idx])
            elif i in ends:
                markup_text += "</span>"
            markup_text += ch
        if len(text) in ends:
            markup_text += "</span>"

        """
        select_id = {}
        for chat_event in chat['events']:
            if chat_event['action'] == 'select':
                select_id[chat_event['agent']] = chat_event['data']

        select = {}
        for agent in [0,1]:
            if not agent in select_id:
                select[agent] = None
                continue
            for obj in chat['scenario']['kbs'][agent]:
                if obj['id'] == select_id[agent]:
                    select[agent] = obj
                    break
        """
        utterances = []

        for utterance in markup_text.split("\n"):
            if utterance.startswith("0:"):
                markup_utterance = Markup("<p class=\"kaiwa-text\">" + utterance + "</p>")
                utterances.append(markup_utterance)
            else:
                markup_utterance = Markup("<p class=\"kaiwa-text\">" + utterance + "</p>")
                utterances.append(markup_utterance)

        if len(selfplay_referents[scenario_id]) > 0:
            referents = selfplay_referents[scenario_id]
        else:
            referents = {}

        select = {}
        for agent in [0,1]:
            for obj in scenario['kbs'][agent]:
                if obj['id'] == selfplay_markables[scenario_id]['selections'][agent]:
                    select[agent] = obj
                    break

        return render_template('selfplay.html',
                                scenario_id=scenario_id,
                                utterances=utterances,
                                kb_0=scenario['kbs'][0],
                                kb_1=scenario['kbs'][1],
                                select_0=select[0],
                                select_1=select[1],
                                instructions=Markup(app.config['coreference_instructions']),
                                markable_ids=markable_ids,
                                markables=selfplay_markables[scenario_id],
                                referents=referents
                                )

webapp/src/web/templates/chat_list.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Chat list</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<style>
  .stat th {
         padding: 0 15px 0 15px;
  }
</style>
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script> 
<script>
         function zero_active() {
            //window.alert("{{chat_id}}");
            $.ajax({
               url: '{{ url_for('admin.zero_active')}}',
               type: "get",
               data: {
               },
               dataType: "json",
               success: function(response) {
                  $('#zero_active_result').text('Successfully zeroed active scenarios')
               }
            });
         }
        function accept_chat(chat_id) {
            $.ajax({
               url: '{{ url_for('admin.accept')}}',
               type: "get",
               data: {
                  "chat_id": chat_id,
                  "review_status": "-1"
               },
               dataType: "json"
            });
         }
         function reject_chat(chat_id) {
            $.ajax({
               url: '{{ url_for('admin.reject')}}',
               type: "get",
               data: {
                  "chat_id": chat_id,
                  "review_status": "-1",
                  "reject_message": ""
               },
               dataType: "json"
            });
         }
         function hello(chat_id) {
            window.alert(chat_id);
         }
</script>
</head>
<body>
  <button type="button" id="zero_active" onclick="zero_active()">Zero Active Scenarios</button><p id='zero_active_result'></p> <br>
  <table class="stat">
    <tr>
      <th>success: {{num_success}}</th>
      <th>fail: {{num_fail}}</th>
      <th>incomplete: {{num_incomplete}}</th>
    </tr>
  </table><br>
  <table class="stat">
    <tr>
      <th>accept: {{num_accept}}</th>
      <th>reject: {{num_reject}}</th>
      <th>not reviewed: {{num_chats - num_accept - num_reject}}</th>
    </tr>
  </table><br>
  <table>
    <tr>
      <th>accept</th>
      <th>reject</th>
      <th>Chat_id</th>
      <th>Outcome</th>
      <th>Review Status</th>
      <th>Dialogue</th>
    </tr>

	{% for i in range(num_chats) %}
	  <tr>
        <td><button type="button" id="accept" onclick="accept_chat('{{chat_ids[i]}}')">Accept</button> <br></td>
        <td><button type="button" id="reject" onclick="reject_chat('{{chat_ids[i]}}')">Reject</button> <br></td>
        <td><a href="{{base_url}}{{ chat_ids[i] }}" > {{ chat_ids[i] }} </a></td>
        <td>{{ chat_outcomes[i] }}</td>
        <td>{{ reviewed[i] }}</td>
        <td>{{ dialogues[i] }}</td>
      </tr>
	{% endfor %}
</table>

</body>

</html>

webapp/src/web/templates/coreference_instructions.html
<h3>Instructions</h3>
<ol>
<li>Please read the <b>dialogue</b> (top right), <b>each player's view</b> and <b>selection</b> (bottom right) carefully to understand how they found the common dot.</li>
<li>Select one of the <span style="background-color:yellow;"><b>highlighted markables</b></span> from the dialogue box.</li>
<li>Based on the dialogue context, <b>click on the dots in the speaker's view</b> which are <b>most likely referred to by that markable.</b></li>
<ul>
    <li> Make sure you understand the <b>whole dialogue context</b> before selecting the dots!</li>
    <li> If the markable is not referring to any dots, you don't need to select any dots.</li>
	<li> If the referents are ambiguous but predictable, please put a check on <b>Ambiguous</b> and select all possible candidates.</li>
    <li> If the referents are not predictable at all, please put a check on <b>Unidentifiable</b> (this should rarely be used).</li>
    <li> Finally, push the <span style="color:green;"><b>Save Button</b></span> and move on to annotate other markables.
    	<!--This will change the markable's color to <span style="background-color:lime;">Normally Annotated</span>, <span style="background-color:violet;">Ambiguous</span> and <span style="background-color:tomato;">Unidentifible</span>.-->
    </li>
</ul>
<li value="4">When you are done annotating all of the markables, you will be able to <span style="color:tomato;"><b>Finish Annotation</b></span> and submit your HIT!
</li>
</ol>

webapp/src/web/templates/finished.html
<html>
    <head>
        <title>Thank You!</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
        <style>
            #content > p {
                font-size:18px;
            }
        </style>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type='text/javascript' src='https://s3.amazonaws.com/mturk-public/externalHIT_v1.js'></script>
        <script type="text/javascript" charset="utf-8">
        	var BASE_URL = 'http://' + document.domain + ':' + location.port;
        	function visualize() {
        		window.location.href = BASE_URL +'/visualize?uid={{uid}}';
        	}
        </script>
    </head>
    <body>
    <div id="content">
        <h2>Find One In Common!</h2>
        <h4>{{ finished_message }}</h4>

	</div>
	<div id="mturk">

    <form name='mturk_form' method='post' id='mturk_form' action="{{turk_submit_to}}/mturk/externalSubmit"><input type='hidden' value='' name='assignmentId' id='assignmentId'/>
    <div>
    <input type='hidden' name='chat_id' value='{{chat_id}}' />
    </div>
    {% if completed %}
    <p><input type='submit' id='submitButton' value='Submit HIT!' /></p></form>
    <script language='Javascript'>turkSetAssignmentID();</script>
    {% endif %}

<!--
		{% if mturk_code is not none %}
		<hr>

		<h3>Thanks for completing this HIT! Please copy and paste this code into the HIT on Mechanical Turk: {{ mturk_code }}</h3>
		{% endif %}
		<hr>
		{% if visualize %}
		<h4><a href="javascript:visualize();">Click here</a> to visualize the dialogue you just completed</h4>
		{% endif %}
	</div>
-->
    </body>
</html>

webapp/src/web/templates/instructions.html
<h3>Your Goal</h3>
<p>You and another user online should have 7 objects in view. However, your view is centered slightly differently from your partner's, and only some objects are in common. Your goal is to <span style="color:#009933">chat with your partner and find one object you have in common!</span></p> 
<h3>Instructions</h3>
<ul>
    <li>Look at <b> your view on the right</b>. </li>
    <li>Use the <b>chat box below</b> to find one object you and your partner have in common. </li>
    <li>Please use <b style="color:#009933">natural sentences</b> as much as possible! </li>
    <ul>
        <li style="color:#009933"> Try to describe your view and ask questions in many ways. </li>
        <li style="color:#FF0000"> Do not use complicated numbers (e.g. 11:59, 1.5cm, 75%). </li>
        <li style="color:#FF0000"> Do not talk about things that are irrelevant to this task. </li>
    </ul>
    <li>Finally, <b>click one object in your view</b> that you found in common. You can select anytime after 1 minute, but <b style="color:#009933">make it very sure you found one object in common!</b> </li>
    <li><b style="color:#FF0000">Please be aware that we will not accept chats which (i) did not follow instructions (ii) did not make good attempt to succeed</b>. If you find problems with the task or your partner, <b> please return and do not submit that HIT</b>. We give additional $0.05 bonus if you successfully find one object in common.</li>
</ul>
</ul>

webapp/src/web/templates/not_annotatable.html
<html>
    <head>
        <title>Thank You!</title>
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/bootstrap.min.css')}}">
        <style>
            #content > p {
                font-size:20px;
            }
        </style>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type='text/javascript' src='https://s3.amazonaws.com/mturk-public/externalHIT_v1.js'></script>
    </head>
    <body>
    <div id="content">
        <h2>Find the Dots in Dialogue!</h2>
        <p><b>Sorry, you have previously annotated this chat. Please check a different HIT! </b></p>
    </div>
    </body>
</html>

webapp/src/web/templates/visualize.html
<html>
   <head>
      <title>{{ chat_id }}</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <style>
         .clearfix {
         overflow: auto;
         }
         .points {
         color: #009933;
         }
         div#chat_container {
         float:left;
         width: 40%;
         }
         div#info_container {
         margin-left: 42%;
         color:#004d00;
         }
         div#icon {
         padding: 10px 100px 10px 20px;
         display: inline-block;
         }
         textarea#chat {
         width: 100%;
         cols: 100;
         height: 25%;
         color:#004d00;
         font-size:14px;
         }
         textarea#reject_message {
         width: 60%;
         cols: 100;
         height: 20%;
         color:#004d00;
         font-size:14px;
         }
         input#text {
         width: 100%;
         }
         td {
         padding: 0 15px 0 15px;
         }
         #instructions > p,li {
         font-size:15px;
         }
         table.sortable th:not(.sorttable_sorted):not(.sorttable_sorted_reverse):not(.sorttable_nosort):after {
         content: " \25B4\25BE"
         }
         table.sortable {
         color:#004d00;
         }
         table { 
         border-collapse: collapse; 
         }
         tr:nth-child(n) { 
         border: solid thin;
         }
         #clockdiv{
         display: inline-block;
         font-weight: bold;
         text-align: center;
         font-size: 18px;
         padding: 15px 0 15px 0;
         }
         #clockdiv > div{
         display: inline-block;
         }
         #clockdiv div > span{
         display: inline-block;
         }
         #clockdiv div > .seconds{
         margin-left:-3px;
         }
      </style>
    	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
      <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/socket.io/1.3.6/socket.io.min.js"></script> 
      <script>
         function accept_chat() {
            //window.alert("{{chat_id}}");
            $.ajax({
               url: '{{ url_for('admin.accept')}}',
               type: "get",
               data: {
                  "chat_id": "{{chat_id}}",
                  "review_status": "{{review_status}}"
               },
               dataType: "json",
               success: function(response) {
                  $('#review_result').text('Accepted')
               }
            });
         }
         function reject_chat() {
            $.ajax({
               url: '{{ url_for('admin.reject')}}',
               type: "get",
               data: {
                  "chat_id": "{{chat_id}}",
                  "review_status": "{{review_status}}",
                  "reject_message": $('#reject_message').val()
               },
               dataType: "json",
               success: function(response) {
                  $('#review_result').text('Rejected')
               }
            });
         }
      </script>
   </head>
   <body>
            <p id='review_result'>{{review_status}}</p>
            <button type="button" id="accept" onclick="accept_chat()">Accept</button> <br>
            <button type="button" id="reject" onclick="reject_chat()">Reject</button> <br><br>
            <!--
            <textarea id="reject_message">{{message}}</textarea>
            -->

            <textarea readonly id="chat">{{chat_text}}</textarea>
            <br>
            {% if survey %}
            <h4>Survey Result</h4>
            <p>0: {{agent_0}}</p>
            <p>1: {{agent_1}}</p>
            <p>cooperative: {{cooperative}}</p>
            <p>humanlike: {{humanlike}}</p>
            <p>comments: {{comments}}</p>
            {% endif %}
            <br>
            <svg width="860" height="430">
               <circle cx="215" cy="215" r="205" fill="none" stroke="black" stroke-width="2" stroke-dasharray="3,3"/>
               {% for item in kb_0 %}
                  <circle cx="{{item['x']}}" cy="{{item['y']}}" r="{{item['size']}}" fill="{{item['color']}}" />
               {% endfor %}
               {% if select_0 %}
               <circle cx="{{select_0['x']}}" cy="{{select_0['y']}}" r="{{select_0['size'] + 2}}" fill="none" stroke="red" stroke-width="2" stroke-dasharray="3,3" />
               {% endif %}
               <circle cx="645" cy="215" r="205" fill="none" stroke="black" stroke-width="2" stroke-dasharray="3,3"/>
               {% for item in kb_1 %}
                  <circle cx="{{430 + item['x']}}" cy="{{item['y']}}" r="{{item['size']}}" fill="{{item['color']}}" />
               {% endfor %}
               {% if select_1 %}
                <circle cx="{{430 + select_1['x']}}" cy="{{select_1['y']}}" r="{{select_1['size'] + 2}}" fill="none" stroke="blue" stroke-width="2" stroke-dasharray="3,3" />
               {% endif %}
            </svg>


   </body>
</html>